# permissions for end users to edit ksdns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ksdns-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ksdns
    app.kubernetes.io/part-of: ksdns
    app.kubernetes.io/managed-by: kustomize
  name: ksdns-editor-role
rules:
- apiGroups:
  - dns.ksdns.io
  resources:
  - ksdns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.ksdns.io
  resources:
  - ksdns/status
  verbs:
  - get
