---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rfc1035.ksdns.io
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rfc1035.ksdns.io
  resources:
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - rfc1035.ksdns.io
  resources:
  - zones/status
  verbs:
  - get
  - patch
  - update
