# permissions for end users to edit zones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zone-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ksdns
    app.kubernetes.io/part-of: ksdns
    app.kubernetes.io/managed-by: kustomize
  name: zone-editor-role
rules:
- apiGroups:
  - rfc1035.ksdns.io
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rfc1035.ksdns.io
  resources:
  - zones/status
  verbs:
  - get
