apiVersion: rfc1035.ksdns.io/v1alpha1
kind: Zone
metadata:
  labels:
    app.kubernetes.io/name: zone
    app.kubernetes.io/instance: zone-sample
    app.kubernetes.io/part-of: ksdns
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ksdns
  name: cluster-1.blahonga.me
spec:
  zone: |
    ; cluster-1.blahonga.me zone
    $ORIGIN cluster-1.blahonga.me.
    @                      3600 SOA   ksdns.blahonga.me (
                                  zone-admin.dyndns.org.     ; address of responsible party
                                  20160727                   ; serial number
                                  3600                       ; refresh period
                                  600                        ; retry period
                                  604800                     ; expire time
                                  1800                     ) ; minimum ttl
                          86400 NS    ksdns.blahinga.me.
                          3600 MX    10 mail.cluster-1.blahonga.me.
                          3600 MX    20 vpn.cluster-1.blahonga.me.
                          3600 MX    30 mail.cluster-1.blahonga.me.
                          3600 TXT   "v=spf1 includespf.ksdns.net ~all"
    mail                  14400 A     204.13.248.106
    vpn                      60 A     216.146.45.240
    webapp                   60 A     216.146.46.10
    webapp                   60 A     216.146.46.11
    service               IN    SRV   8080 10 10 @
