name: Build Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  images:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: build and push images (latest)
        run: make build-and-push-multiarch-images