name: Test
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.17.0"
        env:
          KIND_EXPERIMENTAL_PROVIDER: podman
      - name: test
        run: make test
        env:
          USE_EXISTING_CLUSTER: "true"
      
