name: Build
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test ksdns
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3op
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true
          cache: true
      - name: test
        run: make test
      
