name: Test
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.17.0"
      - name: build and push images (latest)
        run: make docker-buildx && make docker-buildx-zupd
      - name: test
        run: make test
        env:
          USE_EXISTING_CLUSTER: "true"
      
